COPY INTO DEV_CONTOSO_RETAIL.BRONZE.BRONZE_ORDERS
FROM @DEV_CONTOSO_RETAIL.BRONZE.CONTOSO_S3_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_CONTOSO_RETAIL.BRONZE.FF_CSV_CONTOSO')
ON_ERROR = 'CONTINUE';

COPY INTO DEV_CONTOSO_RETAIL.BRONZE.BRONZE_ORDERROWS
FROM @DEV_CONTOSO_RETAIL.BRONZE.CONTOSO_S3_STAGE/orderrows.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_CONTOSO_RETAIL.BRONZE.FF_CSV_CONTOSO')
ON_ERROR = 'CONTINUE';

COPY INTO DEV_CONTOSO_RETAIL.BRONZE.BRONZE_CUSTOMER
FROM @DEV_CONTOSO_RETAIL.BRONZE.CONTOSO_S3_STAGE/customer.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_CONTOSO_RETAIL.BRONZE.FF_CSV_CONTOSO')
ON_ERROR = 'CONTINUE';

COPY INTO DEV_CONTOSO_RETAIL.BRONZE.BRONZE_PRODUCT
FROM @DEV_CONTOSO_RETAIL.BRONZE.CONTOSO_S3_STAGE/product.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_CONTOSO_RETAIL.BRONZE.FF_CSV_CONTOSO')
ON_ERROR = 'CONTINUE';

COPY INTO DEV_CONTOSO_RETAIL.BRONZE.BRONZE_STORE
FROM @DEV_CONTOSO_RETAIL.BRONZE.CONTOSO_S3_STAGE/store.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_CONTOSO_RETAIL.BRONZE.FF_CSV_CONTOSO')
ON_ERROR = 'CONTINUE';

COPY INTO DEV_CONTOSO_RETAIL.BRONZE.BRONZE_DATE
FROM @DEV_CONTOSO_RETAIL.BRONZE.CONTOSO_S3_STAGE/date.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_CONTOSO_RETAIL.BRONZE.FF_CSV_CONTOSO')
ON_ERROR = 'CONTINUE';

COPY INTO DEV_CONTOSO_RETAIL.BRONZE.BRONZE_CURRENCYEXCHANGE
FROM @DEV_CONTOSO_RETAIL.BRONZE.CONTOSO_S3_STAGE/currencyexchange.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_CONTOSO_RETAIL.BRONZE.FF_CSV_CONTOSO')
ON_ERROR = 'CONTINUE';
